# Документ TOML.
[schedule]
	id = "501946"
	[schedule.week1]
		parity_check = "even"
		[schedule.week1.tuesday]
			[schedule.week1.tuesday.1]
			time = "09:50 - 11:20" 
			discipline = "Математический анализ"
			type = "лекция"
			lecturer = "Попов Антон Игоревич"
			classroom = "1405"
			
			[schedule.week1.tuesday.2]
			time = "11:30 - 13:00" 
			discipline = "Математический анализ"
			type = "практика"
			lecturer = "Попов Антон Игоревич"
			classroom = "2316"

			[schedule.week1.tuesday.3]
			time = "13:30 - 15:00" 
			discipline = "Алгебра и алгоритмы"
			type = "лекция"
			lecturer = "Попов Антон Игоревич"
			classroom = "1405"
			
			[schedule.week1.tuesday.4]
			time = "15:30 - 17:00" 
			discipline = "Алгебра и алгоритмы"
			type = "практика"
			lecturer = "Попов Антон Игоревич"
			classroom = "2316"
			
		[schedule.week1.thursday]
			[schedule.week1.thursday.1]
			time = "11:30 - 13:00" 
			discipline = "История российской науки и техники"
			type = "практика"
			lecturer = "Васильев Андрей Владимирович"
			classroom = "2326"
			
			[schedule.week1.thursday.2]
				time = "13:30 - 15:00" 
				discipline = "История российской науки и техники"
				type = "лекция"
				lecturer = "Васильев Андрей Владимирович"
				classroom = "1404"
	[schedule.week2]
		parity_check = "odd"
		[schedule.week2.tuesday]
			[schedule.week2.tuesday.1]
			time = "09:50 - 11:20" 
			discipline = "Математический анализ"
			type = "лекция"
			lecturer = "Попов Антон Игоревич"
			classroom = "1405"
			
			[schedule.week2.tuesday.2]
			time = "11:30 - 13:00" 
			discipline = "Математический анализ"
			type = "практика"
			lecturer = "Попов Антон Игоревич"
			classroom = "2316"

			[schedule.week2.tuesday.3]
			time = "13:30 - 15:00" 
			discipline = "Алгебра и алгоритмы"
			type = "лекция"
			lecturer = "Попов Антон Игоревич"
			classroom = "1405"
			
			[schedule.week2.tuesday.4]
			time = "15:30 - 17:00" 
			discipline = "Алгебра и алгоритмы"
			type = "практика"
			lecturer = "Попов Антон Игоревич"
			classroom = "2316"
		[schedule.week2.thursday]
			[schedule.week2.thursday.1]
			time = "08:10 - 09:40" 
			discipline = "Программирование"
			type = "лабораторная"
			lecturer = "Бобрусь Александр Владимирович"
			classroom = "1333"
			
			[schedule.week2.thursday.2]
			time = "09:50 - 11:20" 
			discipline = "Программирование"
			type = "лабораторная"
			lecturer = "Бобрусь Александр Владимирович"
			classroom = "1333"
			




